Music makes us website
Samuellekpor/Music-Makes-Us pull request #1
Opened 2022-09-16 17:17 UTC by Samuellekpor

This project is about building a website for a music company named Music-makes-us. We made these changes :

1. Create an HTML file and build the skeleton of the project
2. Install linters
3. Create a CSS file with the styling of the project
4. Add a JavaScript file
5. Add images to the images folder created
6. Deploy the project

Please find below the link to our video describing the project: https://www.loom.com/share/b4b9d215bb7b4e868dc1b878d2a3f334

2022-09-16 20:05 UTC, fobadara requested changes
Hi @Samuellekpor, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ Video touches all required aspects in 5 minutes 💯
✅ Lovely commit messages and proper naming of the feature branch 💯
✅ Linters are passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 20:05 UTC, fobadara commented on README.md
> +
- [ ] [OPTIONAL] I think you should tell us about how we can get your project to our locally. Like cloning and things related to it.

2022-09-16 20:05 UTC, fobadara commented on README.md
> +
- [ ] [REQUIRED] You are expected to include the link to your video. in the README not in your pull request.

2022-09-16 20:05 UTC, fobadara commented on index.html
> +          </ul>
- [ ] [REQUIRED] Kindly ensure that your navigation looks like Cindy's design as much as possible. One of the aims of this project is to teach you how to follow templates so that it can be easier in your future workplaces. This applies to the home and. about page

| Your Design | Cindy's Design |
|-------------|-----------------|
|![image](https://user-images.githubusercontent.com/62938735/190710951-26d5d744-cb40-42c7-bb5e-591e40a5fd06.png)|![image](https://user-images.githubusercontent.com/62938735/190711079-b569af40-a3cf-49a4-959c-ccb6fa88d2e6.png)|

2022-09-16 20:05 UTC, fobadara commented on about.html
> +  </footer>
- [ ] [REQUIRED] In Cindy's design the about page has a dark footer while the homepage has a white footer as the background colour. This applies to desktop screen size alone.

2022-09-16 20:05 UTC, fobadara commented on about.html
> +            <button type="button" class="nav-btn">Join Us</button>
- [ ] [REQUIRED] Kindly ensure that your navigation looks like Cindy's design as much as possible. One of the aims of this project is to teach you how to follow templates so that it can be easier in your future workplaces. This applies to the home and. about page

| Your Design | Cindy's Design |
|-------------|-----------------|
|![image](https://user-images.githubusercontent.com/62938735/190710951-26d5d744-cb40-42c7-bb5e-591e40a5fd06.png)|![image](https://user-images.githubusercontent.com/62938735/190711079-b569af40-a3cf-49a4-959c-ccb6fa88d2e6.png)|

2022-09-16 20:05 UTC, fobadara commented on index.html
> +  </div>
- [ ] [REQUIRED] We have four categories of texts in Cindy's design for the homepage. Kindly comply with it.

| Cindy's Design |
|-----------------|
|![image](https://user-images.githubusercontent.com/62938735/190715419-7789713f-a87f-4c11-9226-7e9ac0e7c03c.png)|

2022-09-16 20:05 UTC, fobadara commented on index.html
> +      </div>
- [ ] [REQUIRED] Kindly implement the fix mentioned in the image below.

| Your Design |
|-------------|
|![image](https://user-images.githubusercontent.com/62938735/190716385-9d04adb7-a8a4-467a-8748-361ad8094375.png)|

2022-09-16 20:05 UTC, fobadara commented on index.html
> +    <h2 class="partners-title">Partner</h2>
- [OPTONAL] I think you should pluralize this

2022-09-16 20:05 UTC, fobadara commented on index.html
> +    <span class="separator"></span>
- [ ] [REQUIRED] Kindy implement the following as stated in the image below:
1. Kindly include the chessboard design for all 6 team members.
2. The faint dividers under the `our team` heading and for all 6 team members.

| Cindy's Design |
|----------------|
|![image](https://user-images.githubusercontent.com/62938735/190718551-dc5a8097-d820-45bb-a187-8779e53e562a.png)|

2022-09-16 20:05 UTC, fobadara commented on about.html
> +        <span class="desktop">Throughout our 20-year history our innovative approach has reflected the fast-pace of the music industry itself.</span> We consistantly embrace new technologies, adopt d
- [ ] [REQUIRED] Kindly reduce the text sizes so that it can match Cindy's design

2022-09-16 20:05 UTC, fobadara commented on about.html
> +        </div>
- [ ] [REQUIRED] Kindly reduce the text sizes so that they can match Cindy's design. And move the text up so that they are within the landing page

2022-09-16 20:05 UTC, fobadara commented on about.html
> +      <img class="logo-desc-img" src="images/pngwing.com.png" alt="">
- [ ] [REQUIRED] Kindly reduce the size of this logo

2022-09-16 20:05 UTC, fobadara commented on style.css
> +* {
- [ ] [REQUIRED] Please use the required font-family

2022-09-17 17:12 UTC, emmiiorji approved these changes
Hi @Samuellekpor, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congrats](https://user-images.githubusercontent.com/20554583/190868579-5f71300e-0cde-4d2f-9dd2-34b1476facef.gif)


## Good Highlights ✔

- Changes by previous reviewers implemented
- Good commit messages
- PR is descriptive
- Adherence to GitHub flow

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-17 17:23 UTC, merged

2022-09-19 17:27 UTC, Nemwel-Boniface commented
## Hello @Samuellekpor         :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for meeting all the project requirements good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._